# Generated by Django 4.2.23 on 2026-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("ar", "Arabic"),
                    ("fr", "French"),
                    ("es", "Spanish"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
